// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCGMPCUBtH8OkVFK_4gtadVqIqdF_rZU9M',
    appId: '1:511856634071:web:58ab9ac51bec28872ea892',
    messagingSenderId: '511856634071',
    projectId: 'cafeteria-instituto',
    authDomain: 'cafeteria-instituto.firebaseapp.com',
    storageBucket: 'cafeteria-instituto.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAoKZHZcdYY5BQjMPyYMcNGBMuVekoURwo',
    appId: '1:511856634071:android:f8178398224fb37d2ea892',
    messagingSenderId: '511856634071',
    projectId: 'cafeteria-instituto',
    storageBucket: 'cafeteria-instituto.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBqMS-hocHsdjxD06xsEQXZbvwa8JxiDT8',
    appId: '1:511856634071:ios:e65f80f357160e4a2ea892',
    messagingSenderId: '511856634071',
    projectId: 'cafeteria-instituto',
    storageBucket: 'cafeteria-instituto.appspot.com',
    iosBundleId: 'com.example.cafeteriaInstituto',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBqMS-hocHsdjxD06xsEQXZbvwa8JxiDT8',
    appId: '1:511856634071:ios:391c9ca5ba4f7f492ea892',
    messagingSenderId: '511856634071',
    projectId: 'cafeteria-instituto',
    storageBucket: 'cafeteria-instituto.appspot.com',
    iosBundleId: 'com.example.cafeteriaInstituto.RunnerTests',
  );
}
